name: story_opener
description: Story Opener package
version: 1.0.0
repository: https://github.com/ivangalkindeveloper/story_opener

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
